### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by astrelsky**
Describe the intent of your PR here. Added Windows support, pretty self explanatory and should have been included from the beginning. (I'm aware the llvm and mlir dependencies were the main limiting factor).

## Added
- Added test skip validation for missing gated weights to stabilize local test executions.

## Changed
- Switched to using ``time.perf_counter_ns`` to prevent divide by 0 errors.
- Hoisted object FIFO acquires out of conditional structures to satisfy cyclostatic compiler analysis constraints.
- Swapped shell/awk commands for platform-independent Python execution blocks to handle symbol mapping on Windows.

## PR Merge Checklist

1. [x] The PR is rebased on the latest `devel` commit and pointing to `devel`.
2. [ ] Your PR has been reviewed and approved.
3. [ ] All checks are passing.

```
================================================== warnings summary ===================================================
iron/operators/dequant/test.py::test_dequant[iter0-input_length_1024-num_aie_columns_1-num_channels_1-tile_size_1024-group_size_32]
  D:\IRON\iron\operators\dequant\reference.py:42: UserWarning: torch.quantize_per_tensor, torch.quantize_per_channel and other quantized tensor creation functions that produce tensors with dtype torch.quint8, torch.qint8, and torch.qint32 are deprecated and will be removed in a future PyTorch release. Please see https://github.com/pytorch/pytorch/issues/184982 for more information. (Triggered internally at D:/b/torch/aten/src/ATen/quantized/Quantizer.cpp:116.)
    A = torch.quantize_per_channel(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== 2830 passed, 25 skipped, 1 warning in 1032.96s (0:17:12) ===============================
```
The test run results shown above was faster because I left the build folder in place after realizing how to fix the divide by 0 error I was encountering with the `latency_us` calculations, it had previously taken `2029.72s (0:33:49)`. 

I used the `llvm-aie`, `mlir-aie-no-rtti`  and `mlir-air` that were installed when I installed triton-windows. The restrictions in `requirements.txt` are too strict for the versions and there was no windows wheel for those.

```
llvm-aie                   21.0.0.2026071801+ce8c0f8f
mlir-aie-no-rtti           1.3.4.dev19+g92e9475
mlir-air                   0.0.1.2026071405+c7ee42f.no.rtti
```

### CODE REVIEW

File: iron/common/compilation/base.py [hunk 1]
```diff
@@ -746,13 +746,29 @@ def _prefix_symbols(self, artifact, prefix):
...
+lines = []
+for line in res.stdout.splitlines():
+    parts = line.strip().split()
+    if len(parts) >= 3:
+        sym = parts[-1]
+        lines.append(f"{{sym}} {prefix}{{sym}}\\n")
+with open({repr(symbol_map_file)}, 'w') as f:
+    f.writelines(lines)
+"""
+            nm_cmd = [sys.executable, "-c", python_script.strip()]
```
[the remark this answers is not in the document]
Comment (astrelsky) [reply iron/common/compilation/base.py:813]: It is currently correct. The `strip` call removes the leading and trailing indentation, making it properly indented. Every single test would have failed if there was an indentation error.

File: iron/operators/mha/design.py [hunk 2]
```diff
@@ -554,12 +554,12 @@ def batched_matmul_pv(
...
-                        elem_in_p = of_p.acquire(1)
-                        elem_in_v = of_v.acquire(1)
-                        elt_of_out_scale2 = of_scale.acquire(1)
-
+                
+                for _ in range_(loop_idx_kv - 2):
+                    elem_in_p = of_p.acquire(1)
+                    elem_in_v = of_v.acquire(1)
+                    elt_of_out_scale2 = of_scale.acquire(1)
+                    with if_(loop_idx_kv > 2) as if_op:
```
[the remark this answers is not in the document]
Comment (astrelsky) [reply iron/operators/mha/design.py]: While technically possible, I think it is extremely unlikely. Someone who understands the underlying math and operator will have to take a closer look. This was left unchanged and the only portion that was changed was the locking to fix the compilation errors.

**Review by andrej — COMMENTED** [review]
What are the changes in mha/design.py?

**Comment by astrelsky** [comment]
> What are the changes in mha/design.py?

Fixing the compile error. You cannot use `acquire` and `release` in a conditional statement within a loop, it must be unconditional.


I had to dig up the error.
```
D:\IRON\build\MHA_h1_s16384_d64_kv0_npu2.mlir:415:21: error: 'aie.objectfifo.acquire' op cannot statically analyze cyclostatic acquire pattern: acquire/release is inside a conditional %17 = aie.objectfifo.acquire @outP0(Consume, 1) : !aie.objectfifosubview<memref<64x64xbf16>> ^ D:\IRON\build\MHA_h1_s16384_d64_kv0_npu2.mlir:415:21: note: see current operation: %1586 = "aie.objectfifo.acquire"() <{objFifo_name = @outP0_cons, port = 1 : i32, size = 1 : i32}> : () -> !aie.objectfifosubview<memref<64x64xbf16>> D:\IRON\build\MHA_h1_s16384_d64_kv0_npu2.mlir:2:3: error: Failures have been detected while processing an MLIR pass pipeline aie.device(npu2) { ^ D:\IRON\build\MHA_h1_s16384_d64_kv0_npu2.mlir:2:3: note: Pipeline failed while executing [`AIEObjectFifoStatefulTransform` on 'aie.device' operation: @main]: reproducer generated at `MHA_h1_s16384_d64_kv0_npu2.mlir.prj\resource_alloc_crash.mlir` AIECC COMPILATION FAILED Intermediate MLIR saved to: MHA_h1_s16384_d64_kv0_npu2.mlir.prj\aiecc_failure_1784384099_31012.mlir Repeater script generated: MHA_h1_s16384_d64_kv0_npu2.mlir.prj\aiecc_repeater_1784384099_31012.sh Error: Resource allocation pipeline failed Compilation failed
```

**Comment by andrej** [comment]
Ah, yes, I think that is with a newer MLIR-AIE compiler.

Would you mind submitting an MLIR-AIE upgrade PR including this MHA fix, and this Windows fix separately, since this is unrelated to Windows support?

**Edit:** I might have it the wrong way around, maybe CI is using a newer MLIR-AIE compiler and your local install is older? Please verify, but I have confirmed CI is currently passing for this test.

**Comment by astrelsky** [comment]
> Ah, yes, I think that is with a newer MLIR-AIE compiler.
> 
> Would you mind submitting an MLIR-AIE upgrade PR including this MHA fix, and this Windows fix separately, since this is unrelated to Windows support?

I can. I'm just about out of time for the night unfortunately but I can get to it tomorrow afternoon and I'll take care of the formatting problem as well (I forgot to run it through black). I did however just confirm that the mha changes work with `mlir_aie==1.3.5.dev20+g167f34d`, so it is backwards compatible.

🤔 
```
mlir-aie                   1.3.5.dev20+g167f34d
mlir-aie-no-rtti           1.3.4.dev19+g92e9475
mlir-air                   0.0.1.2026071405+c7ee42f.no.rtti
```

That's problematic.

You appear to be correct and I may have not noticed this at the time. I'll do more testing to figure out what is what tomorrow afternoon and sort it out. Thank you for your patience.

**Comment by astrelsky** [comment]
> Ah, yes, I think that is with a newer MLIR-AIE compiler.
> 
> Would you mind submitting an MLIR-AIE upgrade PR including this MHA fix, and this Windows fix separately, since this is unrelated to Windows support?
> 
> **Edit:** I might have it the wrong way around, maybe CI is using a newer MLIR-AIE compiler and your local install is older? Please verify, but I have confirmed CI is currently passing for this test.

Ok, so it turns out you were correct and that my `mlir-aie` had gotten squashed by the similar package because I wasn't paying attention when I setup the virtual environment. I've reverted that change and fixed the formatting issues and conflict.

**Review by andrej — APPROVED** [review]

**Comment by andrej** [comment]
Awesome. Thank you for your contribution! I will merge this as soon as it passes tests.

One note: We unfortunately currently do not have a Windows CI machine available or bandwidth to keep this tested on Windows (there are very few people working on this repository currently), so please excuse if support breaks again in the future. We welcome future PRs if that happens and thanks again for your help.

**Comment by astrelsky** [comment]
> Awesome. Thank you for your contribution! I will merge this as soon as it passes tests.
> 
> One note: We unfortunately currently do not have a Windows CI machine available or bandwidth to keep this tested on Windows (there are very few people working on this repository currently), so please excuse if support breaks again in the future. We welcome future PRs if that happens and thanks again for your help.

That's fine. It shows be sufficient enough to have copilot check for portability issues and use of unix shell commands and flag it. The hard part of support was really done in the compiler and other components.

**Comment by astrelsky** [comment]
@andrej I didn't realize it until this morning, but the divide by zero error I was encountering in all the tests and claimed to have fixed in a commit message, was actually in `mlir-aie`. I didn't notice because I made the changes to the virtual environment I was using :joy:.

I submitted that fix to `mlir-aie` here https://github.com/Xilinx/mlir-aie/pull/3492.
